[package]
name = "court-coordinator-sdk-maker"
version = "0.1.0"
authors = ["Aritz Beobide-Cardinal <aritz@crownfi.io>"]
edition = "2021"
description = "GLWTPL"
license = "Apache-2.0"
repository = "https://github.com/crownfi/court-coordinator"
private = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
court-coordinator-contract = {path = "../../../contracts/court-coordinator", features = ["library"]}
crownfi-sei-sdk-autogen = {workspace = true}
bpaf = {workspace = true}
color-eyre = {workspace = true}
